### ISSUE TITLE
Please I want to add a field to the response, where should I modify the code?

### ISSUE THREAD

**Issue by wangborong12345** [leothelocust/better-network-chrome-panel#1]
`{
  "msg": "操作成功",
  "code": 200,
  "data": "",
  "payload": "27802c204cd33a955517962e89d9a3eb",
  "errCode": 20000
}`

For example, I want to decrypt the payload and reset it to a new field, where should I add the code. I know this stuff is just for my job.

**Comment by leothelocust** [comment]
@wangborong12345 sorry for the long delay, I didn't have notifications configured correctly.  If you are still wanting to contribute, can you try to provide some additional information about where you expect this to appear on the UI?  Maybe some screenshots and markup to show me what you have in mind.

Also, an example of the input you are wanting to "decrypt", and general method to used to decrypt would help too.  I want to make sure I point you in the right direction.

**Comment by wangborong12345** [comment]
thanks reply,already solved
